name: build
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
        id: go

      - name: git clone
        uses: actions/checkout@v2

      - name: go build
        run: go build -v

      - name: go test
        run: go test -v -cover -coverpkg=./... -race ./...
